---
title: "Non-tabular data"
author: "Sido Haakma"
vignette: >
  %\VignetteIndexEntry{Non-tabular data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



We have now dedicated processes to handle non-tabular data. We now support the following data.

- methylation data

## Methylation data
We use the [methylclock](https://github.com/isglobal-brge/methylclock) package to generate the tabular methylation clocks. Which allows us to upload it to the DataSHIELD backends. 

You can start with uploading the data. The raw data is processed by the `ds-upload` package and the autmatically uploaded to the DataSHIELD backend.

Preparation steps:

- Reformat **id** to **child_id-value**: 
  When you prepared the raw data make sure the ID column in the raw data corresponds with the right child_id in you other data. 
  For instance in the *core* of *outcome* variables. 
- Add *age* information to the methylation data
  When you generate the methylation data you need to add the covariates data as well. 
  You can do this by filling in the input path for the covariate data in the `du.upload.methyl.clock(covariate_data_input_path = "C:\tmp\covariate_data.csv")`
  Make sure you have and "Age" column in the data to use in the clock generation process.

You can generate the clocks and upload to the Armadillo using these commands
  
### Upload to Armadillo


```r
login_data <- data.frame(
  server = "https://armadillo.test.molgenis.org", 
  storage = "https://armadillo-minio.test.molgenis.org", 
  driver = "ArmadilloDriver"
)

library(dsUpload)

du.login(login_data)
  
du.upload.methyl.clocks(
  dict_name = "methylclocks", 
  methyl_data_input_path = "https://github.com/isglobal-brge/methylclock/raw/master/inst/extdata/MethylationDataExample55.csv?raw=true",
  covariate_data_input_path = "https://github.com/isglobal-brge/methylclock/raw/master/inst/extdata/SampleAnnotationExample55.csv?raw=true",
  data_version = "1_0")
```

### Upload to Opal
You can generate the clocks and upload to the Opal using these commands:


```r
login_data <- data.frame(
  server = "https://opal.edge.molgenis.org", 
  username = "administrator", 
  password = "ouf0uPh6", 
  driver = "OpalDriver"
)

library(dsUpload)

du.login(login_data)
#>   Login to: "https://opal.edge.molgenis.org"
#>   Logged on to: "https://opal.edge.molgenis.org"
  
du.upload.methyl.clocks(
  dict_name = "methylclocks", 
  methyl_data_input_path = "https://github.com/isglobal-brge/methylclock/raw/master/inst/extdata/MethylationDataExample55.csv?raw=true",
  covariate_data_input_path = "https://github.com/isglobal-brge/methylclock/raw/master/inst/extdata/SampleAnnotationExample55.csv?raw=true",
  data_version = "1_0")
#> ######################################################
#>   Start upload BETA data into DataSHIELD backend
#> ------------------------------------------------------
#>  * Create temporary workdir
#> ######################################################
#>   Start download dictionaries
#> ------------------------------------------------------
#> * Download: [ mc-yearly-rep.xlsx ]
#>   Successfully downloaded dictionaries
#> ------------------------------------------------------
#>   Start creating project: [ lc_beta_methylclocks ]
#> * Project: [ lc_beta_methylclocks ] already exists
#> ------------------------------------------------------
#>   Start importing dictionaries
#> * Table: [ mc-yearly-rep ] already exists
#> * Import variables into: [ mc-yearly-rep ]
#>   All dictionaries are populated correctly
#> 
#> ── Column specification ───────────────────────────────────────────────────────────────────────────────
#> cols(
#>   ProbeID = col_character(),
#>   GSM946048 = col_double(),
#>   GSM946049 = col_double(),
#>   GSM946052 = col_double(),
#>   GSM946054 = col_double(),
#>   GSM946055 = col_double(),
#>   GSM946056 = col_double(),
#>   GSM946059 = col_double(),
#>   GSM946062 = col_double(),
#>   GSM946064 = col_double(),
#>   GSM946065 = col_double(),
#>   GSM946066 = col_double(),
#>   GSM946067 = col_double(),
#>   GSM946073 = col_double(),
#>   GSM946074 = col_double(),
#>   GSM946075 = col_double(),
#>   GSM946076 = col_double()
#> )
#> 
#> ── Column specification ───────────────────────────────────────────────────────────────────────────────
#> cols(
#>   OriginalOrder = col_double(),
#>   id = col_character(),
#>   title = col_character(),
#>   geo_accession = col_character(),
#>   TissueDetailed = col_character(),
#>   Tissue = col_character(),
#>   diseaseStatus = col_double(),
#>   Age = col_double(),
#>   PostMortemInterval = col_double(),
#>   CauseofDeath = col_character(),
#>   individual = col_double(),
#>   Female = col_double(),
#>   Caucasian = col_logical(),
#>   FemaleOriginal = col_logical()
#> )
#> Warning in predAge(cpgs.imp, coefHannum, intercept = FALSE): The number of missing CpGs for Hannum clock exceeds 80%.
#>   ---> This DNAm clock will be NA.
#> Warning in predAge(cpgs.imp, coefSkin, intercept = TRUE): The number of missing CpGs for Skin clock exceeds 80%.
#>   ---> This DNAm clock will be NA.
#> Warning in predAge(cpgs.imp, coefPedBE, intercept = TRUE): The number of missing CpGs for PedBE clock exceeds 80%.
#>   ---> This DNAm clock will be NA.
#> Warning in predAge(cpgs.imp, coefTL, intercept = TRUE): The number of missing CpGs for TL clock exceeds 80%.
#>   ---> This DNAm clock will be NA.
#>   Login to: "https://opal.edge.molgenis.org"
#>   Logged on to: "https://opal.edge.molgenis.org"
#> * Upload: [ 2021-01-20_17-38-18_methylclocks_1_0.csv ] to directory [ beta ]
#>  * Reinstate default working directory
#>  * Cleanup temporary directory
```

## Troubleshooting
You can run into trouble running the methylation upload into Opal. Here are some answers to questions you can encouter.

### Files are not loaded
If the input files are not picked up directly please make sure the whole input path is specified:

Example: 
```r{specify whole input paths, eval = FALSE}
du.upload.methyl.clocks(
  dict_name = "methylation_clocks", 
  methyl_data_input_path = "C:\Users\yourself\raw_clock_data.csv",
  covariate_data_input_path = "C:\Users\yourself\raw_covariate_data.csv",
  data_version = "1_0")
```

### Cannot allocate vector of size n Mb ...
Running the methylation data generation can be memory consuming. You need to allocate enough memory to perform the action. You can exceute

```r{increase memory size, eval = FALSE}
