knitr::knit("vignettes/dsUpload.Rmd.orig", output = "vignettes/dsUpload.Rmd")
knitr::knit("vignettes/betaDictionaries.Rmd.orig", output = "vignettes/betaDictionaries.Rmd")
knitr::knit("vignettes/dataVersioning.Rmd.orig", output = "vignettes/dataVersioning.Rmd")
knitr::knit("vignettes/dictionaryVersioning.Rmd.orig", output = "vignettes/dictionaryVersioning.Rmd")
knitr::knit("vignettes/qualityControl.Rmd.orig", output = "vignettes/qualityControl.Rmd")
knitr::knit("vignettes/nonTabularData.Rmd.orig", output = "vignettes/nonTabularData.Rmd")
